name: gunzip
description: |
  Decompress a gzip-compressed file using gunzip.
keywords:
  - gunzip
  - decompress
  - gzip
tools:
  - gunzip:
      description: Decompress files compressed with gzip.
      homepage: https://www.gnu.org/software/gzip/
      documentation: https://www.gnu.org/software/gzip/manual/
      licence: ["GPL-3.0-or-later"]
      identifier: ""

input:
  - archive:
      type: file
      description: Gzip-compressed input file.
      pattern: "*.gz"
      ontologies:
        - edam: http://edamontology.org/format_3989 # GZIP format

output:
  gunzip:
    - "${archive.baseName}":
        description: Decompressed output file.
        ontologies: []
  versions:
    - versions:
        type: channel
        description: Channel emitting software version information via the Nextflow `versions` topic.

authors:
  - "@biomina"
maintainers:
  - "@biomina"
